# Generated by Django 4.1.1 on 2022-10-20 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisePlans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Routines',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50)),
                ('day', models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miercoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sabado'), ('7', 'Domingo')], max_length=9)),
                ('ExercisePlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planDeEjercicio.exerciseplans')),
            ],
        ),
        migrations.CreateModel(
            name='Exercises',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=50)),
                ('numeroMaquina', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=250)),
                ('series', models.IntegerField()),
                ('repeticiones', models.IntegerField()),
                ('carga', models.IntegerField()),
                ('descanso_minutos', models.IntegerField()),
                ('video', models.URLField(null=True)),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planDeEjercicio.routines')),
            ],
        ),
    ]
