# Generated by Django 4.1.1 on 2022-10-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planDeEjercicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='routine',
        ),
        migrations.AddField(
            model_name='routines',
            name='Exercise',
            field=models.ManyToManyField(to='planDeEjercicio.exercises'),
        ),
    ]
