# Generated by Django 4.1.3 on 2022-11-26 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_administrators_is_active_and_more'),
        ('planDeEjercicio', '0002_remove_exercises_routine_routines_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseplans',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.members'),
        ),
    ]
