# Generated by Django 4.1.1 on 2022-10-20 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='physicalReports',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateEvaluation', models.DateField()),
                ('objetive', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('heightCM', models.IntegerField()),
                ('cellPhoneNumber', models.CharField(max_length=12)),
                ('cellPhoneNumberEmergency', models.CharField(max_length=12)),
                ('operations', models.CharField(max_length=250, null=True)),
                ('musclePains', models.CharField(max_length=250, null=True)),
                ('sickness', models.CharField(max_length=250, null=True)),
                ('posturalProblems', models.CharField(max_length=250, null=True)),
                ('injuries', models.CharField(max_length=250, null=True)),
                ('categoryAlumn', models.CharField(choices=[('1', 'Principiante'), ('2', 'Experiencia Previa'), ('3', 'Avanzado')], max_length=20)),
                ('weight', models.FloatField()),
                ('AT', models.FloatField()),
                ('percentageOfWater', models.FloatField()),
                ('ATKG', models.FloatField()),
                ('muscleMassKG', models.FloatField()),
                ('valuationPhysical', models.CharField(max_length=50)),
                ('tmb', models.CharField(max_length=250)),
                ('biologicalAge', models.IntegerField(null=True)),
                ('boneMass', models.FloatField(null=True)),
                ('visceralFat', models.CharField(max_length=100, null=True)),
                ('imc', models.CharField(max_length=100, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_physicalReport_set', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trainer_physicalReport_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
