# Generated by Django 4.1.1 on 2022-11-07 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gym', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='trainers',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='members',
            name='gym',
        ),
        migrations.AddField(
            model_name='members',
            name='gym',
            field=models.ManyToManyField(to='Gym.gyms'),
        ),
    ]
