# Generated by Django 4.1.1 on 2022-11-07 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_remove_members_is_active_remove_trainers_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='gym',
            new_name='gyms',
        ),
    ]
