# Generated by Django 4.1.3 on 2022-11-26 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_rename_gym_members_gyms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrators',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='users',
            name='userType',
        ),
    ]
